<!-- 
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
	<div class="page-layout__container">
		<div class="page-layout__view">
			<div class="cl-crud">
				<div class="el-row el-row--flex">
					<el-button size="mini" type="primary" @click="openForm">新增</el-button>
					<div class="cl-flex1"><!----></div>
					<div class="cl-search-key">
						<el-input
							v-model="searchValue"
							size="mini"
							placeholder="请输入关键字"
							class="cl-search-key__input"
						/>
						<el-button size="mini" type="primary" class="cl-search-key__button"
							>新增</el-button
						>
					</div>
				</div>
				<el-row>
					<el-col
						v-for="(o, index) in List"
						class="mod-row"
						:key="o"
						:span="6"
						:offset="index > 0 && index % 3 !== 0 ? 2 : 0"
					>
						<el-card :body-style="{ padding: '0px' }">
							<img :src="o.pic" class="image" style="height: 110px;" />
							<div style="padding: 14px">
								<span>{{ o.title }}</span>
								<div class="bottom">
									<span class="time">{{ o.remark }}</span>
									<el-button type="text" class="button" @click="editForm(o.id)"
										>编辑</el-button
									>
									<el-button type="text" class="button" @click="del(o.id)"
										>删除</el-button
									>
								</div>
							</div>
						</el-card>
					</el-col>
				</el-row>
			</div>
		</div>
	</div>
	<el-dialog v-model="showForm" title="模块管理">
		<addForm
			:form-state="formState"
			:form-id="formId"
			:form-ns="formNs"
			@close="reload"
			v-if="showForm"
		/>
	</el-dialog>
</template>

<script lang="ts">
import { defineComponent, toRefs, reactive, inject, onMounted } from "vue";
import { useRoute } from "vue-router";
import addForm from "./form.vue";
export default defineComponent({
	components: {
		addForm
	},
	props: {},
	setup() {
		const $service = inject<any>("service");
		const state = reactive({
			formState: "create" as string,
			formId: 0 as number,
			showForm: false,
			searchValue: "",
			List: [] as Array<Goods>,
			formNs: {} as { id: number; name: any }
		});
		const route = useRoute();
		const load = async function() {
			const ns = await $service.namespaces.list({ name: route.query.name });
			state.formNs = {
				id: ns[0].id,
				name: route.query.name
			};
			state.List = await $service.goods.list({ namespace: ns[0].id });
		};
		const editForm = function(id: number) {
			state.formId = id;
			state.formState = "edit";
			state.showForm = true;
		};
		const del = async function(id: number) {
			await $service.goods.delete({ ids: [id] });
			load();
		};
		const openForm = function() {
			state.formState = "create";
			state.showForm = true;
		};
		const reload = function() {
			state.showForm = false;
			load();
		};
		onMounted(() => {
			load();
		});
		return {
			del,
			editForm,
			openForm,
			reload,
			...toRefs(state)
		};
	}
});
</script>

<style lang="scss">
.el-input-number.full-width-input,
.el-cascader.full-width-input {
	width: 100% !important;
}
.cl-crud > .el-row {
	flex-wrap: wrap;
	padding-bottom: 5px;
	margin-bottom: 0;
	min-height: 33px;
}
.mod-row {
	margin-top: 10px;
}
.el-form-item--medium {
	.el-radio {
		line-height: 36px !important;
	}

	.el-rate {
		margin-top: 8px;
	}
}

.el-form-item--small {
	.el-radio {
		line-height: 32px !important;
	}

	.el-rate {
		margin-top: 6px;
	}
}

.el-form-item--mini {
	.el-radio {
		line-height: 28px !important;
	}

	.el-rate {
		margin-top: 4px;
	}
}

.clear-fix:before,
.clear-fix:after {
	display: table;
	content: "";
}

.clear-fix:after {
	clear: both;
}

.float-right {
	float: right;
}
</style>

<style lang="scss" scoped>
div.table-container {
	table.table-layout {
		width: 100%;
		table-layout: fixed;
		border-collapse: collapse;

		td.table-cell {
			display: table-cell;
			height: 36px;
			border: 1px solid #e1e2e3;
		}
	}
}

div.tab-container {
}

.label-left-align :deep(.el-form-item__label) {
	text-align: left;
}

.label-center-align :deep(.el-form-item__label) {
	text-align: center;
}

.label-right-align :deep(.el-form-item__label) {
	text-align: right;
}

.custom-label {
}

.static-content-item {
	min-height: 20px;
	display: flex;
	align-items: center;

	:deep(.el-divider--horizontal) {
		margin: 0;
	}
}
</style>
